### ISSUE TITLE
cannot locate theory `Pervasive'

### ISSUE THREAD

**Issue by Max-zhenyuan** [EasyCrypt/easycrypt#115]
I successfully download the easycrypt But it shows 
[critical] [: line -1 (-1)] cannot locate theory `Pervasive'
[\] [-0001] -0.2 % (-1.0B / [frag -1.0B])
what should I do next?

**Comment by vbgl** [comment]
Hello, someone more informed might answer, but my understanding is that this is a bug of the building tool (see https://github.com/ocaml/dune/pull/5192).

Waiting for dune 2.9.2, you may want to use a slightly out-of-date version of EasyCrypt (e.g., at commit b9c76857753141848129e5029c7921eae83bda06).

**Comment by chdoc** [comment]
Another alternative is to not install easycrypt and instead just clone the repository, run `make`, and create a symlink to `ec.native` that is called `easycrypt` and is placed in some directory that is in your `$PATH`. The local binary knows where to find its libraries and the symlink allows ProofGeneral to call easycrypt as it would normally do.

**Comment by Max-zhenyuan** [comment]
> Hello, someone more informed might answer, but my understanding is that this is a bug of the building tool (see [ocaml/dune#5192](https://github.com/ocaml/dune/pull/5192)).
> 
> Waiting for dune 2.9.2, you may want to use a slightly out-of-date version of EasyCrypt (e.g., at commit [b9c7685](https://github.com/EasyCrypt/easycrypt/commit/b9c76857753141848129e5029c7921eae83bda06)).


> Another alternative is to not install easycrypt and instead just clone the repository, run `make`, and create a symlink to `ec.native` that is called `easycrypt` and is placed in some directory that is in your `$PATH`. The local binary knows where to find its libraries and the symlink allows ProofGeneral to call easycrypt as it would normally do.


Thank you so much! I think it is working now by using the way you mentioned. I am a beginner of easycrypt and I don't know how to use this toolset. Where should I start to learn?
