### ISSUE TITLE
when doing elim* => x, maybe restrict x to not be name of procedure parameter, as otherwise confusing precondition?

### ISSUE THREAD

**Issue by alleystoughton** [EasyCrypt/easycrypt#122]
```
type t = [ A | B ].

module M = {
  proc f(z : t) : bool = {
    return z = B;
  }
}.

lemma foo :
  hoare [M.f : exists (w : t), w = B ==> res].  (* not valid *)
proof.
proc.
(*
Current goal

Type variables: <none>

------------------------------------------------------------------------
Context : M.f

pre = exists (w : t), w = B


post = z = B
*)
elim*.
(*
Current goal

Type variables: <none>

------------------------------------------------------------------------
forall (w : t), hoare[ <skip> : w = B ==> z = B]
*)
move => z.  (* perhaps using z here should be disallowed, as z is
               parameter of f, and so the way this is pretty-printed will be confusing? *)
(*
this is confusing, because the z in the precondition isn't the
parameter z, and so isn't the z of the postcondition

Current goal

Type variables: <none>

z: t
------------------------------------------------------------------------
Context : M.f

pre = z = B


post = z = B
*)
auto.
(*
Current goal

Type variables: <none>

z: t
------------------------------------------------------------------------
forall &hr, z = B => z{hr} = B

so this is (correctly) not provable *)
```

**Comment by strub** [comment]
IMO, this is more a problem with the printer that uses ‘z’ for both the logical variable and the program variable.

**Comment by alleystoughton** [comment]
Sure, and then it's a question of inventing notation for the pretty-printer to use.

**Comment by strub** [comment]
Using `z{m}` when `z` resolves both to a logical variable & a program variable?

**Comment by strub** [comment]
@bgregoir What is your take? You're our "notations master" :)

**Comment by bgregoir** [comment]
I don't understand what is the problem. The two expression z and z{m} are already printed in a different way.
Assume the goal is 
  forall z, hoare [M.f: true ==> true]. 
and M.f has a parameter "z". You want to forbid that to ?
I think the situation  has nothing to do this elim*.
Maybe I miss something.

**Comment by strub** [comment]
if they are already printed in a different way, i don't see the problem too.

**Comment by fdupress** [comment]
Printing the postcondition as `z{m} = B` is problematic if we want to (eventually) print only valid formulas.

Tagging program variables with a comment if a logical variable with the same name is in context might work, and might serve to discourage introducing logical variables that shadow program variables that are in explicit use in the goal?

**Comment by alleystoughton** [comment]
Why is this not a "valid formula"? I guess &m is implicit from the context?

**Comment by fdupress** [comment]
There is no `&m` in the context of the goal, only an unnamed final memory that won't be given a name until the program is empty and we've used `skip`.

**Comment by alleystoughton** [comment]
Well, I was thinking that implicit from Context: M.f was some notional memory, call it what you like. When we're in pRHL, these memories are &1 and &2, and that's what would be used in the pretty-printing.

**Comment by alleystoughton** [comment]
Compare with

```
type t = [ A | B ].

module M = {
  proc f(z : t) : bool = {
    return z = B;
  }
}.

lemma foo :
  equiv [M.f ~ M.f : exists (w : t), w = B ==> res{1} /\ res{2}].
proof.
proc.
elim* => z.
(*
Current goal

Type variables: <none>

z: t
------------------------------------------------------------------------
&1 (left ) : M.f [programs are in sync]
&2 (right) : M.f

pre = z = B


post = z{1} = B /\ z{2} = B
*)
```

We could do something similar with Hoare, right?

**Comment by fdupress** [comment]
Seems edgy.

The `{1}` and `{2}` in pRHL are sides, not memories. Otherwise, using them in both pre and post would not make sense.

Does `{m}` become a special tag in Hoare logic that means "the memory at this point in the program"?

**Comment by alleystoughton** [comment]
They aren't memories, just names for memories. If we go one step further in the pRHL proof above, we then quantify using &1 and &2 as actual memories:

```
Current goal

Type variables: <none>

z: t
------------------------------------------------------------------------
forall &1 &2, z = B => z{1} = B /\ z{2} = B
```

I think it's exactly analogous.

**Comment by alleystoughton** [comment]
So we can have

```
Current goal

Type variables: <none>

z: t
------------------------------------------------------------------------
&hr : M.f

pre = z = B


post = z{hr} = B
```

which `skip` transforms into

```
Current goal

Type variables: <none>

z: t
------------------------------------------------------------------------
forall &hr, z = B => z{hr} = B
```

**Comment by fdupress** [comment]
The only time you can use `skip` and get those quantified is exactly when the initial and final memories are the same, and it makes sense to interpret the tags in the pre and post as memories.

In a more complex goal, say `{ z{1} = B /\ z{2} = B } c1 ~ c2 { z{1} = B }`, there are 4 memories that can be referred to explicitly, but only two sides.

The context annotation do not define a memory, but a type of memories (specifying which locals are in scope).

In any case, what I meant initially was that the parser will not parse the post with `{m}`.

**Comment by alleystoughton** [comment]
Yeah, of course it won't parse. Anyway, I don't really think we're disagreeing about the semantics. But I stand by my claim that what I'm proposing for Hoare is just like what we already have in pRHL.

**Comment by fdupress** [comment]
> So we can have
> 
> ```
> Current goal
> 
> Type variables: <none>
> 
> z: t
> ------------------------------------------------------------------------
> &hr : M.f
> 
> pre = z = B
> 
> 
> post = z{hr} = B
> ```
> 
> which `skip` transforms into
> 
> ```
> Current goal
> 
> Type variables: <none>
> 
> z: t
> ------------------------------------------------------------------------
> forall &hr, z = B => z{hr} = B
> ```
> 

We certainly can. I'm not going through and adding `{hr}` after all program variables in my Hoare pres and posts, though.

**Comment by alleystoughton** [comment]
Right, and we don't have to, because unlike in pRHL there is only one side.

**Comment by alleystoughton** [comment]
And because often there is no ambiguity between logical variables and procedure parameters.

**Comment by fdupress** [comment]
So I see two options if we print as `z{hr}`:
1. We print things that don't parse; or
2. We allow tagging of program variables with a special tag `{hr}` that will be ignored, but will issue a warning if they're ignored because of shadowing instead of being ignored because it's not needed. (The current behaviour when a logical variable shadows a program variables.)

**Comment by bgregoir** [comment]
I think we can print z{hr} if there is a logical variable named z.
For the parsing it is more complicated.
Actually, we look first for a logical variable and then for a program variable.
So z{hr} will parse but it will be the logical variable z.
We can try to look for program variable first, but it will create a other problem:
Assume x y are program variable.
((fun x => x) y){hr} will be view as (fun x1 => x{hr}) y{hr}.
Maybe the solution is just to add a special rule in parser/typechecker:
If we view the x{hr} we do a special case : look for prog var first.
So if x is a prog var and a logical variable (x + x){hr} will be interpreted using logical variable but  x{hr} + x{hr} will be interpreted using the prog variable.
In fact it is what is done by the printer. 
We need also to be sure that the printer will add {hr} if there is a logical variable with the same name.

**Comment by strub** [comment]
@bgregoir Your proposal is sound but will make the behaviour of `{hr}` harder to describe and less uniform. What about having a way to say "program variable first" in the syntax? Like `&hr.z` (i.e. use the memory as a namespace) or `z{!hr}`. (Note sure that I convinced myself...)

**Comment by fdupress** [comment]
@alleystoughton noted in a private conversation yesterday that this almost certainly arises already in pRHL, so there is likely no need to come up with a magical parsing solution just for (p)HL.

If we go with special-case parsing, then we might want to look at the pRHL and ambient logic cases again?

**Comment by bgregoir** [comment]
There is nothing specific for (p)HL in what we have discussed. 
Maybe the solution propose by PY with the {!hr} or {!1} is the good one.

**Comment by fdupress** [comment]
Yes. So there are two independent things to do here:
1. Modify pHL and pRHL to allow (optional) annotation of program variables with some memory in pre- and postconditions. (`&hr` works, I tend to use `&0` since it can't be a variable name, so it improves readability slightly)
2. Implement a `{!.}` form of memory tagging that prefers program variables over logical variables if they clash. (And leave the default form of `{.}` to select the logical variable if there's a clash.)

Is that correct and sufficient?

**Comment by bgregoir** [comment]
I think you replace &hr by &0 this will break a lot of dev.
Else we need also to fix the parser such that it use {!.} when needed.

**Comment by alleystoughton** [comment]
> So we can have
> 
> ```
> Current goal
> 
> Type variables: <none>
> 
> z: t
> ------------------------------------------------------------------------
> &hr : M.f
> 
> pre = z = B
> 
> 
> post = z{hr} = B
> ```
> 
> which `skip` transforms into
> 
> ```
> Current goal
> 
> Type variables: <none>
> 
> z: t
> ------------------------------------------------------------------------
> forall &hr, z = B => z{hr} = B
> ```

I'm not clear from the subsequent discussion whether people were pro or con this being part of a solution. (Introducing &hr (or whatever it's called) in the assumptions like &1 and &2 are introduced in pRHL.)

**Comment by strub** [comment]
Ok, let me try to sum up :

  - when you write `z`, EasyCrypt tries to resolve `z` as a logical variable / operator first, and then as a program variable (in the active memory)
  - in HL/pHL, the default active memory is `&hr`. In prHL, there are no default active memory
  - you can locally change the active memory using `e{m}` : in `e`, the active memory is `m`. This is what you do in prHL when using `{1}` or `{2}`
  - when you have a clash between a logical variable (or operator) and a program variable, you cannot access the program variable anymore because of the precedence explained in the first point. In that case, the pretty printer outputs something that cannot be parsed anymore
  - what proposed Benjamin is to consider the expression `z{m}` as resolves `z` in `m` only
  - what I proposed is to have a memory selector of the form `e{!m}` who meaning is `m` is the active memory and takes precedence over logical variables / operators.

**Comment by fdupress** [comment]
So @alleystoughton in your example, the solution we seem to be converging on (using `e{!m}` to give precedence to program variables) will yield

```
Current goal

Type variables: <none>

z: t
------------------------------------------------------------------------
&hr : M.f

pre = z = B


post = z{!hr} = B
`

and

`
Current goal

Type variables: <none>

z: t
------------------------------------------------------------------------
forall &hr, z = B => z{!hr} = B
`

An issue with `e{!m}` is that we have no way of locally overriding it inside of `e` to tag a particular instance of a variable as being logical. But it still seems a lot better than special-casing `z{m}` and switching its meaning from the current one.
