### ISSUE TITLE
Feature Request: replace/set operator for lists (replacing a value at a particular index).

### ISSUE THREAD

**Issue by MM45** [EasyCrypt/easycrypt#123]
Correct me if I am wrong, but there does not seem to be an operator for lists that replaces/sets an element at a certain index. I thought it might be nice to have such an operator. 
Currently, I use the following to accomplish the behavior (i.e., replace the element of list `l` at index `n` with `x`):
`take n l ++ (x :: drop (n + 1) l)`
I am not sure whether it would be desirable to define it in terms of `drop` and `take` (as above, akin to `trim` and `insert`) or make it a stand-alone operator. Regarding out-of-bound indices, I would say it seems most natural to either return the original list (similar to `nth`, but where the default value is not provided by the user and always equals the input) or None (similar to `onth`).
Some useful lemmas I can see concern the interaction of this operator with several other common list operators such as `nth`, `mem`, and `map`. For example, some of the following lemmas could be nice (assuming `replace l n x` replaces element of list `l` at index `n` with `x`):
1. `nth witness (replace l n x) n = x`
2. `map f (replace l n x) = replace (map f l) n (f x) `
2. `nth witness (map f (replace l n x)) n =  f x`
3. `mem (replace l n x) x`

**Comment by chdoc** [comment]
My first question is whether lists really are the data structure you want to use here. What's your use case, and could finite maps (as provided by `SmtMap`) maybe be of help?

**Comment by MM45** [comment]
My current use case essentially concerns a list of elements (public keys) that is constructed by concatenating individual elements one by one until a specific (fixed and predefined) number has been reached. Some time afterward, an element at a random index is replaced by a different element (that was not yet in the list). Also, lists are quite ubiquitous throughout and directly match with what is used by cryptographers (the corresponding pen-and-paper specification/proofs also use lists in these places). Although I think it would be possible to replace lists with finite maps here, it seems quite unnatural to me (but I might be wrong, I am not really experienced with these finite maps).

**Comment by strub** [comment]
@chdoc This is something we already discussed with MM45 in a private conversation. We do want a `replace` operator for lists in his case and having it in the standard library won't hurt.

@MM45 I think that you now have the knowledge to add it on your own in the standard library and to do a PR. I would go with the `take` & `drop` version. Do not hesitate to reach us on Zulip if you need some help.

**Comment by MM45** [comment]
Alright, if I did things correctly, I think I should now have submitted a pull request that solves this issue. Nevertheless, this is my first time doing this, so I am not completely sure if I did everything as desired. Please let me know if anything is out of order.

**Comment by chdoc** [comment]
> Please let me know if anything is out of order.

If you include either `fixes: #123` or `closes: #123` to the description of the PR, then GitHub will automatically link the PR to the issue - which I have now done manually. So, for the next time.
