### ISSUE TITLE
Examples of slow rewrites

### ISSUE THREAD

**Issue by oskgo** [EasyCrypt/easycrypt#131]
I have encountered a rewrite that takes many seconds to complete. This might not be a bug, in which case it could be nice to use for benchmarking.

The example isn't very small, but removing anything improves the performance. I've made it as small as I can.
The final rewrite here takes several seconds to complete.
[Bad.txt](https://github.com/EasyCrypt/easycrypt/files/7987520/Bad.txt)

Similarly, I've started using ```rewrite ...; first done.``` instead of ```rewrite ... //.``` for rewrites that generate trivial goals since the latter has slightly worse performance in my library. This isn't nearly as bad as the first example. They both take just a fraction of a second to complete, but the difference is noticeable in a larger theory. As with the first example the code is a bit too long to inline in an issue.
[Bad2.txt](https://github.com/EasyCrypt/easycrypt/files/7987620/Bad2.txt)

**Comment by fdupress** [comment]
I can't run the examples right now, but does making the operators `opaque` (or `aziomatized`, depending on what you're working with help in this case?

I think it could be that matching is getting lost going down the chains of `offun`s, and those definitions look like the kind you'd like to make opaque, and replace with user reduction rules?

**Comment by oskgo** [comment]
Adding ```axiomatized by test1``` to the end of the definition of ```*^``` in "Bad.txt" made the rewrite instant. Similarly adding it to the end of the definition of ```+``` in the second file made it a lot quicker.

How does ```axiomatized``` work? I try not to use features I don't understand.

I don't know how to make the operators ```opaque```.

**Comment by fdupress** [comment]
`axiomatized by`, in its earliest incarnation, was turning a concrete definition into an abstract declaration equipped with an axiom. (So `op o = e axiomatized by toto.` becomes `op o: t. axiom oE: o = e.`)

I believe it's now a bit more refined internally, and may do exactly what I meant by "making the operator opaque": give it a definition, but mark it so it does not get unfolded by automated tactics (including in matching). @strub would be able to clarify the difference, if there is one, and the mechanism to use for proper opaque operators if it's not `axiomatized by`.

**Comment by oskgo** [comment]
#157 has allowed us to mitigate this issue in a nice way.
