### ISSUE TITLE
renaming bug in BitWord.eca

### ISSUE THREAD

**Issue by alleystoughton** [EasyCrypt/easycrypt#146]
In `BitWord.eca` the below renaming are a bug, as the relevant operators of `Word.eca` are called `mkword` and `ofword`.

```
clone include Word with
  type Alphabet.t    <- bool,
  op   Alphabet.enum <- [true; false],
  op   Alphabet.card <- 2,
  op   n             <- n,
  op   dchar         <- false

proof Alphabet.* by case, ge0_n by apply/ltzW/gt0_n

rename [op] "oflist"  as "bits2w"
       [op] "tolist"  as "w2bits".
```

**Comment by fdupress** [comment]
Thanks, Alley.

What would be your preferred resolution here? Remove the renaming, or fix it so it actually renames things?

**Comment by alleystoughton** [comment]
I guess I'd suggest removing the renamings, as the names used by Word make sense here, too. Someone I'm working with ran into this and couldn't figure out what was going on.
