### ISSUE TITLE
How to build the refman documentation?

### ISSUE THREAD

**Issue by ndcroos** [EasyCrypt/easycrypt#156]
I am trying to build the refman, using `latexmk -pdf refman.tex` 
See:
https://github.com/EasyCrypt/easycrypt-doc/tree/master/refman

However, I get the error `LaTeX Error: File fixme.sty not found.`
I also get errors that other .sty files are missing.
What is the proper way to build the documentation?

**Comment by fdupress** [comment]
Does the `Makefile` in `refman` work?

```bash
cd refman
make
```

It works for me with TeXlive 2021.59745 on linux.
