### ISSUE TITLE
regression on [cost]: simplification of tuple equality should use `/\` instead of `&&`

### ISSUE THREAD

**Issue by fdupress** [EasyCrypt/easycrypt#170]
```
lemma toto (x y : 'a): (x, y) = (y, x).
proof.
move=> /=.
```

yields goal

```
Current goal

Type variables: 'a

x: 'a
y: 'a
------------------------------------------------------------------------
x = y && y = x
```

This is incompatible with the pre-merge behaviour (on b13fb54) of yielding goal `x = y /\ y = x` instead.

**Comment by strub** [comment]
Fixed by [ae4fe92](https://github.com/EasyCrypt/easycrypt/commit/ae4fe9243635b8ec6bdabc4c44aa0f26a16b52a1).
