### ISSUE TITLE
module printing issues: fmap, procedure assignment, local variables/procedures

### ISSUE THREAD

**Issue by chdoc** [EasyCrypt/easycrypt#181]
Consider the following code:
```
require import SmtMap.

module M = { 
  var m : (int * int,int) fmap
  proc p () = { 
    m.[(0,0)] <- 0;
  }
  proc q () = { 
    p();
  }

  proc r = p
}.

print M.
```
This prints:
```
module M = {
  var m : (int * int, int) fmap
  
  proc p() : unit = {
    M.m.[0, 0] <- 0;
  }
  
  proc q() : unit = {
    M.p();
  }
  
  proc r() : unit = M.p
}.

```
1. `m.[0, 0] <- 0` is a parse error, due to the missing parentheses (maybe it shouldn't be)
2. `proc r() : unit = M.p` is a parse error due to arguments and type annotations not being allowed for the `proc p = f` syntax.
3. All local variables are unnecessarily qualified, which can can easily lead to errors when using `print M` as the starting point to define a module `M'`, because the new module then doesn't call its local procedures but those of another module.

**Comment by fdupress** [comment]
Does this supersede or complement #139? Maybe it's worth consolidating?

**Comment by chdoc** [comment]
I think this supersedes #139 . Points (2) and (3) were already mentioned there and the other point mentioned in #139 has indeed been fixed. I saw that there had been changes to the module printing and assumed (without checking) that #139 had been closed.

**Comment by strub** [comment]
Will have a look this afternoon.

**Comment by strub** [comment]
See #621 for the last point. All other points are going to be fixed in the next PR.
