### ISSUE TITLE
library cleanup: `lemma ... by [].`

### ISSUE THREAD

**Issue by fdupress** [EasyCrypt/easycrypt#191]
Let's keep ourselves honest and track this here.

- [ ] Remove or replace all uses of `lemma ... by [].` in the library.
- [ ] Remove special parser support for the construct, to give it a unified `done.` meaning.

**Comment by chdoc** [comment]
AFAIK, `by []` is equivalent to `done` and not `by case`.

**Comment by fdupress** [comment]
You're right.

@strub (bringing the discussion here, where things are ever so slightly less noisy), do you want to keep `by []` in proof bodies? If so, do you want to keep it as a special case in the parser, or should I try to merge its handling with the general case of `by <tactic>` with `<tactic>` a set of focused tactics? (In this case, it would be empty, so it's just `by move.`

**Comment by fdupress** [comment]
The second item in the original list is not actually relevant: there is special parser support also for `by []` in proofs anyway.
