### ISSUE TITLE
logical variable shadows program variable

### ISSUE THREAD

**Issue by chdoc** [EasyCrypt/easycrypt#196]
This is another bug in the series on the interaction of program variables and logical variables (cf. #122 and #136 )
```
require import AllCore.

module M = { proc f(i:int) = { return i; } }.

lemma foo i &m : Pr [ M.f(i) @ &m : res = i ] = 1%r.
proof.
byphoare (: arg = i ==> _). proc. skip => &hr H. 
have -> : i{hr} = 3 by admit. 
(* warning: unused memory `&hr', while typing i *)
(* result: rewrites the [i] on the RHS rather than i{hr} on LHS *)
```
The goal is printed as:
```
i: int
&m: {}
&hr: {i : int}
H: i{hr} = i
-------------------------------------------------------------------------------
i{hr} = 3
```
Note that this is an issue of the interpretation of the equation by `have` (which ignores the memory due to the like-named logical variable, and even gives a warning for this). Rewriting with the assumption `H : i{hr} = i` works as expected in both directions.

**Comment by fdupress** [comment]
The warning was put in place as a resolution to the previous situation.

The short version of the conclusion then was "If you want to put a shotgun to your foot and pull the trigger, we're not here to stop you. But at least we should say something about it."

I am pretty convinced there is *nothing* we can do about this in general. We don't know what local contexts could be opened up when introducing logical variables, and renaming program variables to accommodate existing logical variables sounds like an even more confusing thing to do.

**Comment by chdoc** [comment]
I'm not sure I understand. This is not some hoare logic context with implicit memories and program variables. This is an (almost) purely logical goal where `i` and `i{hr}` are two completely different things and I don't see how one can confuse the two.

**Comment by chdoc** [comment]
Admittedly, the intermediate program judgment after the `proc.` has `pre` and `post` equal to `i = i` and this is basically a short version of #122 , because the LHS `i` is a program variable while the `RHS` variable is the logical variable.

**Comment by fdupress** [comment]
Are you then suggesting that we should resolve this differently from what is proposed in #122 ? (Priority memory selector `{!m}`)
