### ISSUE TITLE
Can't install easycrypt on intel mac, requires dune 2.8

### ISSUE THREAD

**Issue by algebravic** [EasyCrypt/easycrypt#205]
I'm trying to install easycrypt on my mac (osx 12.3.1).  I performed

opam pin -yn add easycrypt https://github.com/EasyCrypt/easycrypt.git

but then

opam install easycrypt

said it required dune >= 2.8, but the most recent version of dune available is 2.7.1.  Is there another source for the newer dune?

opam is version 2.1.2

**Comment by strub** [comment]
Hi,

I suspect that your `opam` repository has not been updated for a while. Have you tried running `opam update`? On my computer, `opam info dune` gives:

```
<><> dune: information on all versions ><><><><><><><><><><><><><><><><><><>  🐫 
name                   dune
all-installed-versions 3.2.0 [default /Users/strubpy/Projects/ProgramProof/upf]
all-versions           1.0.0  1.0.1  1.1.0  1.1.1  1.2.0  1.2.1  1.3.0  1.4.0  1.5.0  1.5.1  1.6.0  1.6.1  1.6.2  1.6.3  1.7.0  1.7.1  1.7.2  1.7.3  1.8.0  1.8.1  1.8.2  1.9.0  1.9.1  1.9.2  1.9.3  1.10.0  1.11.0  1.11.1  1.11.2  1.11.3
                       1.11.4  2.0.0  2.0.1  2.1.1  2.1.2  2.1.3  2.2.0  2.3.0  2.3.1  2.4.0  2.5.0  2.5.1  2.6.0  2.6.1  2.6.2  2.7.0  2.7.1  2.8.0  2.8.1  2.8.2  2.8.4  2.8.5  2.9.0  2.9.1  2.9.2  2.9.3  3.0.2  3.0.3  3.1.0  3.1.1  3.2.0
```

**Comment by algebravic** [comment]
Hi Pierre-Yves.  Thanks for the tip.  I've updated opam.  I was now able to
install easycrypt.  However, now when I do

easycrypt why3config

I get

Prover Z3 version 4.8.17 is not recognized.
  Known versions for this prover: 4.7.1, 4.8.0, 4.8.1, 4.8.3, 4.8.4, 4.8.5,
  4.8.6, 4.8.7, 4.8.8, 4.8.9, 4.8.10, 4.8.11, 4.8.12, 4.8.13, 4.8.14,
4.8.15.
Prover Z3 (alternative: noBV) version 4.8.17 is not recognized.
  Known versions for this prover: 4.7.1, 4.8.0, 4.8.1, 4.8.3, 4.8.4, 4.8.5,
  4.8.6, 4.8.7, 4.8.8, 4.8.9, 4.8.10, 4.8.11, 4.8.12, 4.8.13, 4.8.14,
4.8.15.
Prover Z3 (alternative: counterexamples) version 4.8.17 is not recognized.
  Known versions for this prover: 4.8.7, 4.8.8, 4.8.9, 4.8.10, 4.8.11,
  4.8.12, 4.8.13, 4.8.14, 4.8.15.

I installed z3 via homebrew.  Apparently the only version of z3 available
with that is 4.8.17.  Is there something else that I need to do?

**Comment by strub** [comment]
We are limited by the provers and provers' versions supported by Why3 and it is safer to downgrade to a supported version of Z3. You can tell Homebrew to install an older version:

```
brew tap-new $USER/local-z3
brew extract --version=4.8.15 z3 $USER/local-z3 
brew install z3@4.8.15
```

**Comment by algebravic** [comment]
Thanks!  That worked after I also did

brew link --overwrite ***@***.***

Victor
