### ISSUE TITLE
unsoundness of `fission` tactic

### ISSUE THREAD

**Issue by chdoc** [EasyCrypt/easycrypt#210]
It turns out that one can use fission to split a loop that increments two variables in lockstep for a random number of iterations into two loops that do so for the variables individually, each with their own random number of iterations. 

I didn't go all the way to proving false, but I'm pretty sure that `E.foo` always returns `true` and that `E.bar` returns `false` with nonzero probability. 

CC: @ethanlee515 (who came up with the example)
```
require import AllCore DBool.

module E = { 
  var i,j : int
  proc foo () = {
    var c;
    i <- 0;
    j <- 0;
    c <- false; 
    while (!c) { 
      i <- i + 1;
      j <- j + 1;
      c <$ {0,1};
    } 
    return i = j;
  }

  proc bar () = {
    var c;
    i <- 0;
    j <- 0;
    c <- false; 
    while (!c) { 
      i <- i + 1;
      c <$ {0,1};
    } 
    c <- false; 
    while (!c) { 
      j <- j + 1;
      c <$ {0,1};
    }
    return i = j;
  }
}.

equiv bad : E.foo ~ E.bar : true ==> ={res}.
proof.
proc. 
fission{1} 4!1 @1,2. by sim.
qed.

**Comment by ethanlee515** [comment]
The `fusion` tactic is broken in a similar way: one can use it to merge two while-loops in an unsound way. Here is an alternative "proof" of the `bad` lemma above, using `fusion` this time.
```
equiv bad2 : E.foo ~ E.bar : true ==> ={res}.
proof.
proc.
fusion{2} 4!1 @1,1. by sim.
qed.
```

**Comment by strub** [comment]
First, I am surprised that we still have these 2 TCB tactics. Anyway, the epilog should not be accepted when not deterministic.
