### ISSUE TITLE
if using <> as datatype constructor, impossible to write corresponding match clause

### ISSUE THREAD

**Issue by alleystoughton** [EasyCrypt/easycrypt#215]
Presumably the following was intended to work. Instead the match clause gave an error saying the constructor was unknown. (Fix PR to follow. I'm not sure whether anyone really wants to use <> as a constructor, but the parser tried to allow this.)

```
require import AllCore.

type t = [
  | (<>) of int & int
].

print (<>).
(*
* In [operators or predicates]:

op (<>) : int -> int -> t = < 1-th constructor of t >.
*)

op f (x : t) : int =
  match x with
  | y <> z => y + z
  end.
```

**Comment by alleystoughton** [comment]
I'm going to rephrase this....

**Comment by strub** [comment]
Dup of #217
