### ISSUE TITLE
problem with using <> as a datatype constructor

### ISSUE THREAD

**Issue by alleystoughton** [EasyCrypt/easycrypt#217]
It is currently possible to define a datatype with <> as a constructor:

```
type t = [
  | (<>) of int & int
].
```

Then `print (<>).` gives

```
* In [operators or predicates]:

op (<>) : int -> int -> t = < 1-th constructor of t >.
```

There is a bug in the parser rule for match clauses that makes the above unusable:

```
| x1=bdident op=loc(NE) tvi=tvars_app? x2=bdident
    { PPApp ((pqsymb_of_symb op.pl_loc "[!]", tvi), [x1; x2]) }
```

Replacing "[!]" with "<>" would make the following match possible:

```
op f (x : t) : int =
  match x with
  | y <> z => y + z
  end.
```

But the way that "<>" is treated in expressions means that `x <> y` always means "!(x = y)". 

Consequently, my thinking is that "<>" should be disallowed as a datatype constructor, and then the rule that tried to allow it in a match should be removed.

**Comment by alleystoughton** [comment]
Hi Pierre-Yves, yes, I in fact just tried using the abbreviation mechanism and removing the special parser rules. It looks promising to me. Shall I do a PR so you can look at it?

**Comment by strub** [comment]
Just checked on my side (there are only 3 rules) and it works. But yes, please, do the PR.
