### ISSUE TITLE
`rnd*` tactic bugged?

### ISSUE THREAD

**Issue by ethanlee515** [EasyCrypt/easycrypt#220]
Minimal example below.

```
require import AllCore.
require import Distr.

type V.
op g : V -> V.
op dV : V distr.

module Bad = {
  proc f() = {
    var w, v;
    v <$ dV;
    w <- g v;
    return (v, w);
  }

  proc f'() = {
    var w, y;
    y <$ dV;
    w <- g y;
    return (y, w);
  }
}.

lemma bad : equiv[Bad.f ~ Bad.f' : true ==> ={res}].
proof.
proc.
rnd: *0 *0; auto.
(* goal contains nonsense *)
```

Here I want to prove that `Bad.f` and `Bad.f'` are equivalent. This is trivially true, as the programs are in sync (up to renaming local variables). When I tried the `rnd*` tactic, I expected it to generate some trivial proof obligation to the effect of "`dmap dV (fun v => (v, g v))` is equal to itself". The tactic currently instead asks me to prove that `dmap dV (fun v => (v, g v)) = dmap dV (fun y => (g y, y))`, which is unfortunately untrue. On the right hand side, `g` is applied on the wrong element.

**Comment by strub** [comment]
`rndsem` has been changed s.t. the variables in the final left-value follows respect the order `x < y` iff `x is written before y in the initial program`.
