### ISSUE TITLE
Merge `drestrict` & `dfilter`.

### ISSUE THREAD

**Issue by strub** [EasyCrypt/easycrypt#233]
Currently, the standard library contains two related operators on distributions: `drestrict p d` (that filters `d`, keeping the events that validate `p`) and `dfilter p d` (that filters `d`, removing the events that validate `p`). Note that `dfilter` uses a naming convention that is against the one used for `List.filter` and `FSet.filter`.

Given that there is a direct relation between `drestrict` & `dfilter`, it is questionnable to have these two operators.

We might want to merge these two definitions.

**Comment by chdoc** [comment]
@fdupress Do we know of uses of `dfilter` outside of the EC libraries. 

Inside the libraries, the only library that imports `Dfilter` is `Dexcepted`, the latter being used in several places. 

I would propose to deprecate the entire `Dfilter` theory and port `Dexcepted` to `drestrict`. Thoughts? Comments?
