### ISSUE TITLE
Local module visible outside of section

### ISSUE THREAD

**Issue by ethanlee515** [EasyCrypt/easycrypt#245]
I was able to prove a (non-local) lemma which references a local module. In particular, I would close my section and `print` my lemma, and still see the local module in the lemma statement. @chdoc says it’s a bug and I should open an issue. Minimal example below.

First, I set up a toy security game. I define an oracle type that our adversary can access. Roughly speaking, our `Game` initializes `O.win` to `false`, and the oracle doesn’t allow the adversary to change it to `true`; we therefore can say that the adversary never "wins".

```
module type Oracle = {
  proc f() : unit
}.

module type Oracle_i = {
  include Oracle
  proc init() : unit
}.

module OMain : Oracle_i = {
  var win : bool
  proc init() = {
    win <- false;
  }
  proc f() = { }
}.

module type Adv(O: Oracle) = {
  proc main() : bool
}.

module Game(O: Oracle_i)(A: Adv) = {
  proc main() = {
    O.init();
    A(O).main();
  }
}.
```

Let me first briefly give an "idiomatic" proof that the adversary never wins, in a way that does not make use of my Easycrypt bug. I will later present my faulty code following a similar structure, but with certain alterations. Here I declare an adversary that cannot read or write the oracle `OMain`. I next define a local `OAlt` that is an alternative (but equivalent) characterization of `OMain`. I prove everything in terms of `OAlt`, then finally use `conseq` to show that my analysis on `OAlt` carries over to `OMain`. Everything should hopefully look standard.

```
section Good.

declare module A <: Adv { -OMain }.

local module OAlt = {
  var win : bool
  proc init() = {
    win <- false;
  }

  proc f() = { }
}.

local equiv eq_O :
  Game(OMain, A).main ~ Game(OAlt, A).main : ={glob A} ==> OMain.win{1} = OAlt.win{2}.
proof.
proc.
inline*; sp.
call(_: !OMain.win{1} /\ !OAlt.win{2}); last by auto.
proc; by auto.
qed.

local lemma alt_result :
  hoare[Game(OAlt, A).main: true ==> !OAlt.win].
proof.
proc. inline*. sp.
call(_: !OAlt.win); last by auto.
proc; by auto.
qed.

lemma good_result :
  hoare[Game(OMain, A).main: true ==> !OMain.win].
proof.
conseq eq_O alt_result => /#.
qed.

end section Good.
```

When we `print good_result`, the outputs are what we'd expect.
```
lemma good_result:
  forall (A(O : Oracle) <: Adv{+all mem, -OMain} [main : {O.f} ]),
    hoare[ Game(OMain, A).main : true ==> !OMain.win].
```

Now, let me finally illustrate the bug. This time I define `OAlt` before the adversary. Consequently, I have to restrict the adversary from reading or writing not only `OMain` but also `OAlt`, or else I wouldn't be able to prove `alt_result`. The rest of my analysis follows similarly.

```
section Bad.

local module OAlt = {
  var win : bool
  proc init() = {
    win <- false;
  }

  proc f() = { }
}.

declare module A <: Adv { -OMain, -OAlt }.

local equiv eq_O :
  Game(OMain, A).main ~ Game(OAlt, A).main : ={glob A} ==> OMain.win{1} = OAlt.win{2}.
proof.
proc.
inline*; sp.
call(_: !OMain.win{1} /\ !OAlt.win{2}); last by auto.
proc; by auto.
qed.

local lemma alt_result :
  hoare[Game(OAlt, A).main: true ==> !OAlt.win].
proof.
proc. inline*. sp.
call(_: !OAlt.win); last by auto.
proc; by auto.
qed.

lemma bad_result :
  hoare[Game(OMain, A).main: true ==> !OMain.win].
proof.
conseq eq_O alt_result => /#.
qed.

end section Bad.
```

We have now closed the `Bad` section, so we expect the local module `OAlt` to become inaccessible. Correspondingly, the `-OAlt` restriction given to the adversary is no longer meaningful and intuitively should vanish. That is however not what happens. When we `print bad_result`, we get the following output:
```
lemma bad_result:
  forall (A(O : Oracle) <: Adv{+all mem, -OMain, -Top.OAlt} [main : {O.f} ]),
    hoare[ Game(OMain, A).main : true ==> !OMain.win].
```

Specifically, now we have an `-Top.OAlt` restriction, which appears to be nonsense. At this point, we tried `print OAlt` and `print Top.OAlt`; both output "no such object in any category".

**Comment by fdupress** [comment]
Yup. Two options to fix:
1) Prevent local modules from appearing a restrictions in non-local lemmas; or
2) Remove local modules from restriction lists in non-local lemmas when closing a section.

2 is extra-logical, and feels like a massive trust assumption.

1 will lead to frustrating behaviour if we do it only upon parsing the lemma. We should be able to reject also a `declare module ...` where the restriction list contains a local module. The only cases where this would prevent a valid proof is when the section does not contain any non-local lemmas (which could occur while drafting).

A quick note that this is not just a proof cosmetic bug (where we expose outside a section the existence of a local module), but actually prevents further application of `bad_result` other than to a fully concrete adversary: it is impossible to quantify over an adversary restricted to not overlap with `Top.OAlt` (`unknown module: Top.OAlt`).

**Comment by strub** [comment]
@fdupress Option 1. seems to be the more sensible here. This is what is done when having a local lemma of the form:

```
local lemma L (A <: Adv { -OMain, -OAlt }) : ...
```

**Comment by fdupress** [comment]
I think this doesn't address the potential confusion where the proof author might not immediately understand where that restriction comes from if the failure only pops up when they write the lemma.

But perhaps that's good enough?

**Comment by strub** [comment]
The restriction is now enforces when you write `declare A <: ...`. What I said is that the behaviour is now in line with what happens when you write a lemma parameterised by a abstract module with restrictions in its type.
