### ISSUE TITLE
Various failures when cloning theories.

### ISSUE THREAD

**Issue by strub** [EasyCrypt/easycrypt#247]
Reported by @ethanlee515 on Zulip:

```
require Matrix.

theory TA.
clone Matrix as MA.
end TA.

theory TB.
clone Matrix as MB.
end TB.

clone TA as IA.

(* Error: unknown symbol: Top.IB.MB.Vector.offun0E *)
clone TB as IB with
  theory MB <- IA.MA.
```

```
require PROM.

theory TA.
type X, Y.
op [uniform lossless] dY : Y distr.
clone import PROM.FullRO as RO with
  type in_t <- X,
  type out_t <- Y,
  op dout <- fun _ => dY.
end TA.

theory TB.
type X, Y.
op [uniform lossless] dY : Y distr.
clone import PROM.FullRO as RO with
  type in_t <- X,
  type out_t <- Y,
  op dout <- fun _ => dY.
end TB.

type X, Y.
op [uniform lossless] dY : Y distr.

clone TA as RA with
  type X <- X,
  type Y <- Y,
  op dY <- dY.

(* anomaly: "Assert_failure src/ecSubst.ml:55:2" *)
clone TB as RB with
  type X <- X,
  type Y <- Y,
  op dY <- dY,
  theory RO <- RA.RO.
```

**Comment by fdupress** [comment]
The first problem was an issue with not using `<=`, so the best fix we could propose is 1) extending the error message with a recommendation; and 2) documenting the feature. (Ah!)

The second remains even with `<=` (as per @ethanlee515's message on Zulip). Yi, can you confirm the error message is the same (and that the assertion failure is at the same line)?

**Comment by strub** [comment]
First point has been addressed and will be merged soon.

Second point can be simplified to:

```
require import AllCore.

theory T.
module type X = {}.
module X = {}.
end T.

theory U.
  clone T.
end U.

clone U as CU with theory T <- T.
```

**Comment by ethanlee515** [comment]
> The first problem was an issue with not using `<=`, so the best fix we could propose is 1) extending the error message with a recommendation; and 2) documenting the feature. (Ah!)
> 
> The second remains even with `<=` (as per @ethanlee515's message on Zulip). Yi, can you confirm the error message is the same (and that the assertion failure is at the same line)?

Yes, error message stays the same.

**Comment by ethanlee515** [comment]
> First point has been addressed and will be merged soon.
> 
> Second point can be simplified to:
> 
> ```
> require import AllCore.
> 
> theory T.
> module type X = {}.
> module X = {}.
> end T.
> 
> theory U.
>   clone T.
> end U.
> 
> clone U as CU with theory T <- T.
> ```

@chdoc and I noticed in this example that if we change one of the two `X`s to `Y`, then the proof compiles successfully. So the issue is basically a name clash?

**Comment by strub** [comment]
Yes, named have to be the same for the bug to appear.

**Comment by chdoc** [comment]
Unfortunately, `RO : RO` is pretty widespread in proofs. ^^

**Comment by strub** [comment]
The idea is to fix the bug, not to work around it.

**Comment by chdoc** [comment]
Since I cannot find a PR, I will comment here on trying out `deploy-fix-247-2`:

When I try to substitute an RO theory while cloning I get weird axiom warnings:
```
require PROM. 

abstract theory T.
  type a,b.
  op dout : b distr.

  clone PROM.FullRO as PRO with
    type in_t <- a,
    type out_t <- b,
    op dout <- fun _ => dout
  proof*.
end T.

clone PROM.FullRO as MyPRO.

type my_a, my_b.
op my_d : my_b distr.

clone import PROM.FullRO as PRO with
  type in_t <- my_a,
  type out_t <- my_b,
  op dout <- fun _ => my_d.

section FOO.

clone T as MyT with
  type a <- my_a,
  type b <- my_b,
  op dout <- my_d,
  theory PRO <- PRO
proof*.

(* Prints:

+ global axiom dout_ll in section

+ global axiom dout_ll in section

+ global axiom enum_spec in section

*)
```
However, I fail to find any `dout_ll` lemma in the context, be it at the top level, in `T` or in `MyT`. Somewhat worryingly, when I turn the clone into a local clone the warnings go away. Unfortunately, I cannot print MyT as this runs against #51, which is still not fixed.

**Comment by strub** [comment]
I think that your last remark reduces to:

```
theory T.
  abstract theory U.
    axiom L : false.
  end U.
end T.

section S.
  clone T as CT.
end section S.
```

This is a false warning.
