### ISSUE TITLE
"anomaly: Removed"

### ISSUE THREAD

**Issue by chdoc** [EasyCrypt/easycrypt#268]
The following triggers `anomaly: Removed`

```
require import AllCore.

require Matrix.

abstract theory Foo.
  type Rq.
  clone import Ring.ComRing as RqRing with type t <= Rq.
end Foo.

abstract theory Bar.
  clone import Matrix as M.
end Bar.

clone import Foo as MyFoo.

clone import Matrix as MatRq with 
  theory ZR <= MyFoo.RqRing.

clone import Bar as MyBar with 
  theory M <- MatRq.

```
Note: using `<=` instead of `<-` avoids the anomaly, but this introduces a lot of aliases into the context, requiring either to look past heaps of `(...)%M.Matrix....` or (when importing `M`) risk getting yelled at by EC that there are multiple matching operators at every corner.

**Comment by bgregoir** [comment]
I think the idea of <= was precisely to not introduce aliases: ie. the operator exists but the typing should not view it.

**Comment by strub** [comment]
This was a "bug-a-la-con"
