### ISSUE TITLE
Installation prefix settings

### ISSUE THREAD

**Issue by arthuraa** [EasyCrypt/easycrypt#269]
I am trying to install EasyCrypt as a Nix derivation. I have created a derivation in a `shell.nix` file that downloads and compiles one of the recent commits, following the `default.nix` file in the current repository. The compilation proceeds fine, but the installation fails because dune attempts to install EasyCrypt in the path of OCaml's derivation, rather than inside the path of EasyCrypt itself. And it is doing this despite the fact that the derivation includes `PREFIX=$(out)` under `installFlags`.

I don't know much about Nix or dune, but I have been able to fix the problem by adding a patch command to the derivation as follows:

```
    prePatch = ''
      substituteInPlace Makefile --replace ") install" ") install --prefix \$(PREFIX)"
    ''
```

This has the effect of adding `--prefix $(PREFIX)` to the `$(DUNE) install` command of the `Makefile`.

Is this the right way to invoke dune in this situation? Should EasyCrypt's `Makefile` be updated accordingly?

**Comment by fdupress** [comment]
Thanks. There is a branch `deploy-new-nix`, which includes a new derivation from current HEAD (and a somewhat clean shell setup which also sets up the python path correctly). There's something wonky going on with he CI that needs investigated before we merge, still. (A job that shouldn't be running has been stuck in the pipeline for a month.)

I'm not sure if trying to direct dune is the right way of going about it. Are you able to check if the patched Makefile also then works with opam-based setups?

**Comment by arthuraa** [comment]
It's nice to hear that there is a fix underway. I have incorporated the new `default.nix` into my workflow, and it seems to be working great. I don't think it's necessary to patch the `Makefile` given that this works.
