### ISSUE TITLE
Bind EasyCrypt to Lia.

### ISSUE THREAD

**Issue by strub** [EasyCrypt/easycrypt#277]

**Comment by lyonel2017** [comment]
I've started in bracnh https://github.com/EasyCrypt/easycrypt/tree/feature-micromega to implement a tactic that allows you to call Coq from Easycrypt. So we can call Micromega tactics, like `lia`, after preprocessing with `zify`.

**Comment by lyonel2017** [comment]
In the current version of branch https://github.com/EasyCrypt/easycrypt/tree/feature-micromega it is now possible to use Micromega by calling Coq. However, I've changed a few things in the SMT generation, so testing is required. In addition, examples are needed to show that this new feature is useful. And, the naming convention for .v files needs improvement.

**Comment by strub** [comment]
Fixed by #467
