### ISSUE TITLE
Kill `admit`s in the standard library

### ISSUE THREAD

**Issue by strub** [EasyCrypt/easycrypt#280]

**Comment by chdoc** [comment]
If #295 gets merged, there are 2 admits remaining: 

One (in `ZModP.ec`):
```
(*FIXME*)
lemma exp_sub_p_1 (x : zmod) :
  unit x =>
  exp x (p - 1) = one.
proof.
admitted.
```
IIUC, this is actually a formulation of Fermat's little theorem. I'm not sure we want to spend the effort to prove this in EC. It's not used in EC (other than to prove the other formulation of the theorem). 

Two (in `DJoin.ec`): 
```
equiv Sample_Loop_eq: S.sample ~ S.loop: ={d, xs} ==> ={res}.
proof. admitted.
```
This one seems manageable, and it is actually used in `DHIES`.

**Comment by strub** [comment]
All fixed.
