### ISSUE TITLE
failure to infer that a type is a pair

### ISSUE THREAD

**Issue by oskgo** [EasyCrypt/easycrypt#333]
The following code fails even though it should be possible to infer that `x` is a tuple:
```
op foo ['a]: ('a -> bool) -> 'a -> bool.

op bar = foo (fun x => x.`1 = x.`2) (true, true).
```
Adding a type annotation makes this succeed:
```
op bar = foo (fun (x: _ * _) => x.`1 = x.`2) (true, true).
```

**Comment by fdupress** [comment]
Unfortunately, we can't infer that it's a pair: the projectors are generic in the size of the tuple.

You can fix it for pairs by using `fst` and `snd` instead of the generic projectors.

**Comment by oskgo** [comment]
EasyCrypt cannot infer the size of the tuple from the `(true, true)` input?

**Comment by strub** [comment]
Superseded by #630

As François said, we are not even using a bidirectional type-checker.
