### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by markreyn** [EasyCrypt/easycrypt#364]
After cloning the repository and installing all dependencies I tried a simple
     make clean && make
This produced an error on line 154 of ecProvers.ml saying
     Driver.load_driver_for_prover
is unbound.

I need to build from source to add tcl/tk functionality via the labltk package

A little help please?

**Comment by strub** [comment]
Hi. Which version of Why3 did you install?

**Comment by markreyn** [comment]
Why3 1.6.0

**Comment by markreyn** [comment]
branch "main"

**Comment by strub** [comment]
> Why3 1.6.0

IMO, you must have some left-overs from a previous installation of Why3. Can you check the version of Why3 in the output of `ocamlfind list`?

**Comment by strub** [comment]
Hi. Did you fix your problem?

**Comment by markreyn** [comment]
Yes thank you. The why3 library was 1.5Not 1.6Sent from my iPhoneOn Apr 21, 2023, at 1:43 AM, Pierre-Yves Strub ***@***.***> wrote:﻿
Hi. Did you fix your problem?
