### ISSUE TITLE
clone import as abstract

### ISSUE THREAD

**Issue by AntoineSere** [EasyCrypt/easycrypt#370]
In the following, when using `clone import` , the theory `Bar` end up not being abstract:

```
abstract theory Foo.
  type t.
end Foo.

clone import Foo as Bar.

print Foo.
print Bar.
```

Is there a way currently in EasyCrypt to modify this example to make `Bar` abstact? If not, I think it may be good to have.

**Comment by chdoc** [comment]
Not sure what you're trying to achieve here. The idea of cloning an abstract theory is to turn it into a concrete theory. If the surrounding theory is abstract, the inner theory should also be effectively abstract.

**Comment by fdupress** [comment]
I can't EasyCrypt at the moment, but I'm here. Does `abstract clone Foo as Bar` work?

Note that you can't import an abstract theory (because it doesn't exist until made concrete), so `abstract clone import Foo as Bar` would fail in any case.

**Comment by chdoc** [comment]
Both `clone abstract` and `abstract clone` are parse errors. However, if you want a second abstract copy of `Foo` named `Bar`, how about:
```
abstract theory Bar.
  clone include Foo.
end Bar.
```
As mentioned above, you cannot `import` things that do not (yet) exist.

**Comment by fdupress** [comment]
Thanks for checking @chdoc.

If this is something that is useful generally (most of our theories do end up being semi-concrete anyway, and abstract sub-theories of concrete theories are useful to hide proof gunk), we should certainly parse `abstract clone Foo as Bar with ...` as

```
abstract theory Bar.
  clone include Foo with ...
end Bar.
```

@AntoineSere can you point to the file and general location in your branch that would benefit from this?

**Comment by chdoc** [comment]
Can we close this issue then?
