### ISSUE TITLE
renaming a specific theory

### ISSUE THREAD

**Issue by AntoineSere** [EasyCrypt/easycrypt#371]
In the following example, the renaming changes the name of the theory `Bar` to `Foo`, but also of the theory `FooBar` to `FooFoo`:

```
abstract theory Foo.
  abstract theory Bar.
    abstract theory FooBar.
      type t.
    end FooBar.
  end Bar.
end Foo.

clone import Foo as FooFoo
  rename [theory] "Bar" as "Foo".
print FooFoo.
```

Is there currently a way in EasyCrypt to perfor the first renaming without performing the second, ie to target a specific theory  `Bar` instead of all the theories with `Bar` in their name? If not , I think it would be good to have, as well as the same thing for anything that can be renamed (operators, lemmas, etc...).

**Comment by chdoc** [comment]
I think this applies to the renaming of operators and lemmas as well. Have you tried multiple renamings, i.e., first rename `FooBar` into something that does not contain `Bar` and the rename it back afterwards. Not that this is a particularly nice/clean solution, even if it were to work.

**Comment by fdupress** [comment]
The left-hand side should be an `re` regexp. Can you try using start of line and end of line markers to delimit `Bar`? (In general regexp languages, that would be `^Bar$`; not sure what `re` uses for this.)

**Comment by fdupress** [comment]
Just ssh'ed home. This works.
