### ISSUE TITLE
Performance issues with ocaml 5

### ISSUE THREAD

**Issue by fdupress** [EasyCrypt/easycrypt#390]
Triggering this requires a large context I cannot include here, and only affects interactive usage of EasyCrypt—while pretty-printing large proof goals for display. As far as I can tell, it cannot be triggered through non-interactive testing.

I have tried bisecting recent commits on pretty printing to no avail, then tested different versions of ocaml, since only one of my computers displayed the behaviour.

For constant easycrypt version, computer, proof context and printed goal:
- With ocaml 4.14.2, printing is instant.
- With ocaml 5.0.0, printing takes a few minutes and eats up 7GB of RAM that is not GC'd before printing the next goal. 4 interactions ate up my RAM and swap and crashed my machine.

We should advise against using ocaml 5 until we understand what causes the behaviour and how to address it. I have no clue how to investigate this further.

**Comment by fdupress** [comment]
https://github.com/ocaml/ocaml/issues/12269

This suggests some problems with thread spawning and failure handling in 5.0, fixed by 5.1.

Unfortunately, 5.1 currently fails to compile batteries 3.6, so I can't test.

**Comment by strub** [comment]
We don't spawn threads in EC.

**Comment by fdupress** [comment]
> We don't spawn threads in EC.

Does Why3 spawn threads for SMT solvers?

Anyhow, trying to help reproduce and track down so we can figure out if it fits known ocaml 5 bugs or if we should raise.

`DynMatrix.eca` and `DHIES.ec` appear to exhibit this behaviour well in the standard library.
Both reached above 3GB of RAM usage (5GB for DHIES) with Ocaml 5, but stayed *well* under 500MB with Ocaml 4.14.1.

All other memory usage was also a bit higher, but whatever those two do a lot of compared to other theories is probably what we should be looking at for explaining the massive memory regression.

**Comment by chdoc** [comment]
For `DynMatrix` we had quite a few issues with slow rewrites. If memory serves me right, this was mitigated but not completely eliminated by locking certain operators. Other than that, it is mostly "pure math".

**Comment by kayceesrk** [comment]
> I have no clue how to investigate this further.

If there is a reproduction case, the OCaml compiler devs will be happy to investigate.

**Comment by strub** [comment]
OCaml 5.1 fixes the issue.
