### ISSUE TITLE
Small issues in runtest

### ISSUE THREAD

**Issue by sarranz** [EasyCrypt/easycrypt#404]
From the Jasmin side we found the following issues a while back, you might want to check on them.

6: `collections` is not used
159: `_parse_timeout` doesn't seem to be used
162: you want `parser`, not `parse`
329: the module `logging` wasn't imported
325: `scenario` is not used
364: lambda is unnecessary (because `scenario` is not used)
374: lambda is unnecessary
621: `success` is not used
666: `TIMING_DIR` is not defined (`--timing` crashes)
744: `ok` is not used

**Comment by strub** [comment]
Thank you for the report. The script is now lint'ed to catch these errors at the source.
