### ISSUE TITLE
try fails with smt

### ISSUE THREAD

**Issue by Slukoo** [EasyCrypt/easycrypt#424]
Some commands like:

> try smt().

or

> do! (smt() || simplify).

fail when smt() fails to prove the goal, not sure if this is intentional, but it can be annoying in some situations.

**Comment by fdupress** [comment]
This is intentional: it allows us to also support a weak-check mode (and others like a delayed-check/batch-check mode) that can construct the proof tree assuming all SMT calls succeed.
