### ISSUE TITLE
How can I use .eco file?

### ISSUE THREAD

**Issue by Unlimitosu** [EasyCrypt/easycrypt#459]
I got a `.ec` file from Jasmin, and got a `.eco` file by running `easycrypt filename.ec`.

How can I use this `.eco` file? It has a lot of entries with direct, kind, and digest fields.

If it's the wrong way to execute `.ec` file, how can I execute it?

**Comment by fdupress** [comment]
The .eco file is just there to speed up checking of files whose context hasn't changed: it keeps track of enough information to avoid rerunning EasyCrypt when the file, its dependencies and EasyCrypt (including solvers) haven't changed since the last run.

**Comment by Unlimitosu** [comment]
@fdupress Then how can I use `.eco` file? I want to run a `.ec` file but I really don't know how to execute it.

I run EasyCrypt in Ubunto terminal, not a ProofGeneral.

**Comment by fdupress** [comment]
You don't use a .eco file.

EasyCrypt (generates and) uses it automatically if you run it on the corresponding .ec file.

**Comment by Unlimitosu** [comment]
But when I run Easycrypt with `easycrypt filename.ec`, it does not show anything. How can I check it? or showing nothing is normal?

**Comment by strub** [comment]
`easycrypt` shows a progress bar when checking the file. Once done, unless there is an error, nothing is printed. (The same way `gcc` does not print anything when the compilation is successful)

**Comment by Unlimitosu** [comment]
Ok I got it, and there is one more question remaining.

I ran `SchnorrPK.ec` in the `example` directory, and I got the following outputs:

```
unlimit@ubuntu:~/Downloads/test$ easycrypt SchnorrPK.ec 
* In [lemmas or axioms]:/ [frag -1.0B])

lemma schnorr_proof_of_knowledge_completeness:
  forall (h : group) (w' : exp) &m,
    R h w' => Pr[Completeness(SchnorrPK).main(h, w') @ &m : res] = 1%r.

* In [lemmas or axioms]:/ [frag -1.0B])

lemma schnorr_proof_of_knowledge_special_soundness:
  forall (h : statement) (msg : group) (ch ch' r r' : exp) &m,
    ch <> ch' =>
    g ^ r = msg * h ^ ch =>
    g ^ r' = msg * h ^ ch' =>
    Pr[SpecialSoundnessExperiment(SchnorrPK, SchnorrPKAlgorithms).main
       (h, msg, ch, r, ch', r') @ &m : res <> None /\ R h (oget res)] =
    1%r.

* In [lemmas or axioms]: / [frag -1.0B])

lemma schnorr_proof_of_knowledge_shvzk:
  forall (D <: SigmaTraceDistinguisher) &m,
    Pr[SimulateHonestVerifier(SchnorrPK, SchnorrPKAlgorithms, D).gameIdeal
       () @ &m : res] =
    Pr[SimulateHonestVerifier(SchnorrPK, SchnorrPKAlgorithms, D).gameReal
       () @ &m : res].
```

What does the printed code mean?

+ Is there any basic syntax guide of EasyCrypt?
