### ISSUE TITLE
problem with automatic unfolding of operators at point marked by "/" in operator's declaration

### ISSUE THREAD

**Issue by alleystoughton** [EasyCrypt/easycrypt#507]
Automatic unfolding of operators when arguments have been supplied up to the "/" point in an operator's declaration was added by commit `480c0ea6498bb31d7a24896588723f12fba9d97d`. But as the following examples show, it's working in a curious way, in which `rewrite /=` and `simplify` are different, and sometimes running `simplify` after `rewrite /=` makes more progress.

```
require import AllCore List.

op g (x : int) / = x + 1.

lemma goo (x : int) :
  g x = x + 1.
proof.
simplify.
(*
nothing happens:

Current goal

Type variables: <none>

x: int
------------------------------------------------------------------------
g x = x + 1
*)
rewrite /=.
(*
Current goal

Type variables: <none>

x: int
------------------------------------------------------------------------
true
*)
trivial.
qed.

op f (x : int) / (y : int) = x + y.

lemma foo (x y : int) :
  f x = (+) x.
proof.
simplify.
(*
nothing happens:

Current goal

Type variables: <none>

x: int
y: int
------------------------------------------------------------------------
f x = (+) x
*)
rewrite /=.
(*
something happens, but another
simplification does more:

Current goal

Type variables: <none>

x: int
y: int
------------------------------------------------------------------------
(fun (y0 : int) => x + y0) = (+) x
*)
simplify.
(*
Current goal

Type variables: <none>

x: int
y: int
------------------------------------------------------------------------
true
*)
trivial.
qed.
```

**Comment by strub** [comment]
There are two issues here. The first one is that `simplify` does not use the same reduction configuration as `/=`. I can change that, but `simplify` should be considered deprecated.

The second one looks more like a incompleteness in the reduction engine.

**Comment by alleystoughton** [comment]
What does auto invoke, wrt simplification.? I got the impression it was simplify not rewrite /=.
