### ISSUE TITLE
cannot prove goal (string)

### ISSUE THREAD

**Issue by lifepillar** [EasyCrypt/easycrypt#53]
I get  the message in the subject whenever I execute `smt`, no matter how trivial is the result I want to prove. I guess that my configuration is not right yet. Using macOS, these are the steps I have performed to install EasyCrypt:

```
brew install ocaml opam
opam init
eval $(opam env)
pam pin -yn add easycrypt https://github.com/EasyCrypt/easycrypt.git
opam install depext 
opam depext easycrypt
opam install --deps-only easycrypt
opam install alt-ergo
why3 config --detect --full-config
opam install easycrypt
```

The output of why3 was this:

```
Found prover Coq version 8.13.0, but no Why3 libraries were compiled for it
0 prover(s) added
Generating strategies:
Save config to /Users/me/.why3.conf
```

Not sure that `0 prover(s) added` is expected at this point (shouldn't it find `alt-ergo`?). Anyway, if I try something trivial in EasyCrypt, such as:

```
require import Int.
lemma foo x: x+x = x+x.
proof.
smt.
```

`smt` results  in `cannot prove goal (string)`. I have tried installing Z3 v4.8.10 and reconfiguring Why3, but that version does not seem supported:

```
brew install z3
why3 config --detect --full-config
```

gives me: 

```
Prover Z3 version 4.8.10 is not known to be supported.
Known versions for this prover: 4.8.0, 4.8.1, 4.8.3, 4.8.4, 4.8.5, 4.8.6.
Known old versions for this prover: .
Found prover Coq version 8.13.0, but no Why3 libraries were compiled for it
1 prover(s) added (including 1 prover(s) with an unrecognized version)
```

And then the same EasyCrypt session as above results in:

```
prover Z3 exited with HighFailure
<tty>: line 4 (0-3): cannot prove goal (strict)
```

**Comment by fdupress** [comment]
You are right, why3 should find alt-ergo. Can you check that opam sets your PATH properly? If so, can you check that alt-ergo is indeed in your PATH?

For Z3, you'll need to fetch 4.8.6 from the Z3 release page (or check the dockerfile for a quick command): Z3 is moving much faster than Why3's release cycle and this is causing all sorts of failures where Why3 no longer connects the uninterpreted symbols it knows to those Z3 knows. (I had some luck with 4.8.7 and 4.8.8, but things started *really* breaking down with 4.8.9.)

**Comment by alleystoughton** [comment]
I think one also needs version 2.3.1 of Alt-Ergo for why3 to be happy:

opam install alt-ergo.2.3.1

**Comment by lifepillar** [comment]
Thanks! Installing alt-ergo.2.3.1 indeed did the trick:

```sh
$ why3 config --detect --full-config
Found prover Alt-Ergo version 2.3.1, OK.
Found prover Coq version 8.13.0, but no Why3 libraries were compiled for it
1 prover(s) added
Generating strategies:
  Prover Alt-Ergo 2.3.1 will be used in Auto level >= 1
```

And now `smt` kicks in. For Z3, I'll try with 4.8.6.

You should maybe add a check for supported alt-ergo versions, as is done for Z3? Or  at least update the Readme.

**Comment by alleystoughton** [comment]
We will certainly update the README, but it's not a check we can add, as I understand it. What I don't understand is why Why3 isn't telling us what versions of Alt-Ergo it's happy with. Or am I missing something? We don't want the README to say, "if you have Why3 1.3.3, then ...". I'm unsure what language to put in the README that won't be version specific.

**Comment by lifepillar** [comment]
>Can you check that opam sets your PATH properly?

Yes, it prepends `/Users/me/.opam/default/bin` to my `PATH`. And `alt-ergo` is in `PATH`:

```
$ which alt-ergo
/Users/me/.opam/default/bin/alt-ergo
```

>What I don't understand is why Why3 isn't telling us what versions of Alt-Ergo it's happy with

So, maybe this is an upstream issue?

**Comment by alleystoughton** [comment]
Yes, it's a problem with Why3, not EasyCrypt.

**Comment by fdupress** [comment]
alt-ergo 2.3.x takes a `-version` CLI argument; 2.4.0 takes `--version`... I'll look through closed issues in the Why3 gitlab, but that smells like something they fixed as soon as it happened and not yet released.

On the plus side, it means the stdlib has been going through without alt-ergo for a while...
