### ISSUE TITLE
GIT hash not up-to-date

### ISSUE THREAD

**Issue by MQuaresma** [EasyCrypt/easycrypt#549]
The 'GIT hash' information shown when starting an EC shell is not up-to-date **i.e.** doesn't match the actual version/release that was compiled.

The following is a screenshot of the output when compiling release 2024.01:
![Screenshot 2024-05-23 at 16 13 19](https://github.com/EasyCrypt/easycrypt/assets/10332749/330f6169-4040-43dd-a9bf-967d50dcec5e)

**Comment by fdupress** [comment]
This is because `dune subst` uses a set of flags for `git describe` that ignores lightweight tags.

Using annotated tags to tag releases would ensure that the description stops at latest release.

**Comment by fdupress** [comment]
That being said, @MQuaresma, the git hash displayed does contain enough information for you to figure out what to check out, in this case, the commit whose hash starts with `g2b3bbad`.

**Comment by fdupress** [comment]
@strub do you want to try and address this retrospectively by annotating existing tags, or take it on board for future releases?

**Comment by strub** [comment]
We should annotate the tags that relate the releases. I'll give it a try.

**Comment by strub** [comment]
This works on my side:

```
>> Copyright (c) 2012 IMDEA Software Institute
>> Copyright (c) 2012 Inria
>> Copyright (c) 2017 Ecole Polytechnique
>> Copyright (c) EasyCrypt contributors (see AUTHORS)
>> Distributed under the terms of the MIT license
>> Standard Library (theories/**/*.ec): 
>> 	Distributed under the terms of the MIT license
>> 
>> GIT hash: r2024.01-48-gddcc091-dirty
[0|check]>
```
