### ISSUE TITLE
Error "anomaly: EcLowGoal.InvalidProofTerm" raised while attempting to use congr tactic on goal stating equality of edivz.

### ISSUE THREAD

**Issue by MM45** [EasyCrypt/easycrypt#66]
Trying to use the `congr` tactic on the following goal leads to a "anomaly: EcLowGoal.InvalidProofTerm" error.

```
Current goal

Type variables: <none>

z : Zq
ez: int
ltp_z: asint z < p
------------------------------------------------------------------------
edivz (shl (asint z) (eq - ep)) q = edivz (shl (asint (Zq2Zp z)) (eq - ep)) q
```
Moreover, adapting this goal to an equivalent one by (only) replacing the left-hand side's `eq - ep` by `eq - ep - 0` prevents the error from being raised, with the `congr` tactic working as expected. To be precise, on the following goal, no error is raised and the `congr` tactic works as expected.
```
Current goal

Type variables: <none>

z : Zq
ez: int
ltp_z: asint z < p
------------------------------------------------------------------------
edivz (shl (asint z) (eq - ep - 0)) q =
edivz (shl (asint (Zq2Zp z)) (eq - ep)) q
```

**Comment by strub** [comment]
I cannot reproduce. The bug must has been solved.
