### ISSUE TITLE
[Question] Link between Why3 and EasyCrypt

### ISSUE THREAD

**Issue by amelieled** [EasyCrypt/easycrypt#660]
Hi everyone,
Do you use Why3 as backend in order to use many ATP/ITP or also as a verification condition generator?
I'm also very curious about the fact that you are using Why3 1.7/1.8 and not the current version.

**Comment by strub** [comment]
Hi. We use Why3 only as a backend to ATP. I think that we are targeting the last version of Why3 (1.7.x). What do you mean by "the current version"?
