### ISSUE TITLE
rewrite //= in does nothing

### ISSUE THREAD

**Issue by AntoineSere** [EasyCrypt/easycrypt#68]
Using the `rewrite //= in H.` on the following goal does not modify it.

```
Current goal

Type variables: <none>

H : 0 + 0 = 0
------------------------------------------------------------------------------------------------------------------
forall (x y : int), x + y = y + x
```
While using the `rewrite /= in H.` on the following goal gives:

```
Current goal

Type variables: <none>

H : true
------------------------------------------------------------------------------------------------------------------
forall (x y : int), x + y = y + x
```

I would expect both tactics to behave the same way as the second tactic currently does.

The following file was used to generate the aforementioned goals:

[Rewrite_Simpl_In.txt](https://github.com/EasyCrypt/easycrypt/files/6599963/Rewrite_Simpl_In.txt)

**Comment by fdupress** [comment]
The semantics of `//=` are that it does nothing if it can't *close* the goal. What *closing* means on a hypothesis is a bit fuzzy but my expectation is that a hypothesis is "closed" when it reduces to `false`.

Indeed, using `rewrite //= in H` in the following configuration does close the goal. (And so does `rewrite // in H`.)

```
Current goal

Type variables: <none>

H : 0 + 1 = 0
------------------------------------------------------------------------------------------------------------------
forall (x y : int), x + y = y + x
```

Why do you expect `//=` to behave in the same way as `/=`?

**Comment by strub** [comment]
> The semantics of `//=` are that it does nothing if it can't _close_ the goal. 

No, the intro-pattern `//=` is a synonym for `simplify; try done`.

**Comment by fdupress** [comment]
> > The semantics of `//=` are that it does nothing if it can't _close_ the goal.
> 
> No, the intro-pattern `//=` is a synonym for `simplify; try done`.

Yeah. My bad.

I'm still confused as to why we'd want them to do the same thing here, though; although I do agree (now that my brain is on) that we should expect `//=` to do at least as much as `/=`. Should the `try done` part not apply *within* the hypothesis `H` in which we're doing the rewrite to drop it if it becomes trivial?
