### ISSUE TITLE
`dletE` and related lemmas

### ISSUE THREAD

**Issue by chdoc** [EasyCrypt/easycrypt#91]
The current collection on lemmas about `mu` and `dlet` seems suboptimal. In particular, we have: 

```
lemma dlet1E ['a, 'b]:
  forall (d : 'a distr) (f : 'a -> 'b distr) (b : 'b),
    mu1 (dlet d f) b = sum (fun (a : 'a) => mu1 d a * mu1 (f a) b).
lemma dletE ['a, 'b]:
  forall (d : 'a distr) (f : 'a -> 'b distr) (P : 'b -> bool),
    mu (dlet d f) P =
    sum (fun (b : 'b) =>
      sum (fun (a : 'a) => if P b then mu1 d a * mu1 (f a) b else 0%r)).
lemma dletE_swap ['a, 'b]:
  forall (d : 'a distr) (f : 'a -> 'b distr) (P : 'b -> bool),
    mu (dlet d f) P =
    sum (fun (a : 'a) => 
      sum (fun (b : 'b) => if P b then mu1 d a * mu1 (f a) b else 0%r)).
lemma dletE_mu ['a, 'b]:
  forall (d : 'a distr) (F : 'a -> 'b distr) (E : 'b -> bool),
    mu (dlet d F) E = sum (fun (x : 'a) => mu1 d x * mu (F x) E).
```
- The lemma `dletE_mu` was recently added by by me and should probably be named `dletE`. 
- The original `dletE` and `dletE_swap` lemmas are useful in their own right, but should get new names.
- The lemma `dlet1E` is actually just an instance of `dletE_mu`, but I suggest keeping it for the sake of consistency. 

@strub @bgregoir do you have some suggestions?

**Comment by bgregoir** [comment]
> On 4 Nov 2021, at 13:32, Christian Doczkal ***@***.***> wrote:
> 
> 
> The current collection on lemmas about mu and dlet seems suboptimal. In particular, we have:
> 
> lemma dlet1E ['a, 'b]:
>   forall (d : 'a distr) (f : 'a -> 'b distr) (b : 'b),
>     mu1 (dlet d f) b = sum (fun (a : 'a) => mu1 d a * mu1 (f a) b).
> lemma dletE ['a, 'b]:
>   forall (d : 'a distr) (f : 'a -> 'b distr) (P : 'b -> bool),
>     mu (dlet d f) P =
>     sum (fun (b : 'b) =>
>       sum (fun (a : 'a) => if P b then mu1 d a * mu1 (f a) b else 0%r)).
> lemma dletE_swap ['a, 'b]:
>   forall (d : 'a distr) (f : 'a -> 'b distr) (P : 'b -> bool),
>     mu (dlet d f) P =
>     sum (fun (a : 'a) => 
>       sum (fun (b : 'b) => if P b then mu1 d a * mu1 (f a) b else 0%r)).
> lemma dletE_mu ['a, 'b]:
>   forall (d : 'a distr) (F : 'a -> 'b distr) (E : 'b -> bool),
>     mu (dlet d F) E = sum (fun (x : 'a) => mu1 d x * mu (F x) E).
> The lemma dletE_mu was recently added by by me and should probably be named dletE.
          Fully agree with this.
> The original dletE and dletE_swap lemmas are useful in their own right, but should get new names.
          did we have a lemma that say 
            mu d E = sum (fun x => mu1 d x * b2r E x) ?
          they look like a direct consequence of dletE and this. 
         dlet_muM ?
          I am very bad with name ...
         
 
> The lemma dlet1E is actually just an instance of dletE_mu, but I suggest keeping it for the sake of consistency.
yes

**Comment by strub** [comment]
> did we have a lemma that say mu d E = sum (fun x => mu1 d x * b2r E x) ?

This is by definition:

axiom muE ['a] (d : 'a distr) (E : 'a -> bool):
  mu d E = sum (fun x => if E x then mass d x else 0%r).

**Comment by strub** [comment]
- `dletE_mu` -> `dletE`
 - `dletE` -> `dletE_muE` (because basically, you're unfolding 2 definitions)
 - `dletE_swap` -> `dletE_muE_swap`
