### ISSUE TITLE
error when clone importing the same theory twice

### ISSUE THREAD

**Issue by mortensol** [EasyCrypt/easycrypt#92]
In the following code, I try to `clone import Bigop` for both real numbers and integers, as well as the matrix theory for real numbers and integers: 

```
require import Int Real. 
require Matrix Bigop.    

clone import Bigop as BigR with
  type     t      <- real,
   op Support.idm <- 0%r,
   op Support.(+) <- Real.(+)
proof * by smt(@Real). 

clone import Bigop as BigI with
  type     t      <- int,
   op Support.idm <- 0,
   op Support.(+) <- Int.(+)
proof * by smt(@Int).  

clone import Matrix as IntMatrix with 
  type ZR.t <- int,
   op  ZR.(+) <- Int.(+). 

clone import Matrix as RealMatrix with
  type ZR.t <- real,
   op  ZR.(+) <- Real.(+).
```

This works fine for Bigop, but the second `clone import Matrix` results in the error `unknown type ZR.t `. 

Also, `clone Matrix as IntMatrix` followed by `clone import Matrix as RealMatrix` followed by `import IntMatrix` does not produce the same error. Is there a reason for this?

```
clone Matrix as IntMatrix with 
  type ZR.t <- int,
   op  ZR.(+) <- Int.(+). 

clone import Matrix as RealMatrix with
  type ZR.t <- real,
   op  ZR.(+) <- Real.(+). 

import IntMatrix. 
```

**Comment by strub** [comment]
Hi. I think that you hit a bug.

**Comment by fdupress** [comment]
Not a bug: there is a theory Matrix.Matrix which is the one that gets
cloned if you import IntMatrix first.

Possibly a bug in the Matrix library.

**Comment by strub** [comment]
François found the issue (The `Matrix` top theory contains a `Matrix` & `Vector` subtheory).

**Comment by fdupress** [comment]
@mortensol You can refer to the original top-level Matrix theory using `Self.Matrix`, I think.
