### ISSUE TITLE
`op (\)` printed in prefix style

### ISSUE THREAD

**Issue by chdoc** [EasyCrypt/easycrypt#93]
In `Dexpected` we have
```
op (\) (d : 'a distr) (P : 'a -> bool) : 'a distr = dscale (dfilter d P).
```
Inside the file, this operation is written in infix style, but the goals all display the operation in prefix style:
```
lemma nosmt dexcepted1E_in d P (x:'a):
  P x => mu1 (d \ P) x = 0%r.
```
leads to a goal statement printed as `P x => mu1 (\ d P) x = 0%r`. I assume this is a bug/regression?

**Comment by strub** [comment]
i think this is a bug that appears when we added the possibility to have prefix operators of the form `opname`.

**Comment by chdoc** [comment]
So what determines whether things are prefix or infix?

**Comment by strub** [comment]
They should all be an infix notation. This must be a silly bug in the pretty printing.
